# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Qiaosen Huang's Tech Space 
email: joeosnw@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Tech enthusiast. Currently working on Node.js and Golang. 
  Loveeeeeeeeee large distributed system architecture designing!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joeosnw.github.io" # the base hostname & protocol for your site
github_username:  joesonw
disqus: joesonw

# Build settings
markdown: kramdown
